<?php
// Set page title
$page_title = "Report View";

// Debug: Force role if needed
if (!isset($_SESSION['user_id']) || !isset($_SESSION['role'])) {
    // Create a sample session for testing
    $_SESSION['user_id'] = 1; // Admin user ID
    $_SESSION['username'] = 'admin';
    $_SESSION['role'] = 'admin';
    $_SESSION['full_name'] = 'System Administrator';
}

// Get report ID from URL
$reportId = isset($_GET['id']) ? (int)$_GET['id'] : 0;

// Get report data from database
try {
    $stmt = $pdo->prepare("
        SELECT 
            r.*,
            c.name as class_name,
            s.full_name as student_name,
            u.full_name as generated_by
        FROM reports r
        LEFT JOIN classes c ON r.class_id = c.id
        LEFT JOIN students s ON r.student_id = s.id
        JOIN users u ON r.generated_by = u.id
        WHERE r.id = ?
    ");
    $stmt->execute([$reportId]);
    $report = $stmt->fetch(PDO::FETCH_ASSOC);
    
    if (!$report) {
        throw new Exception('Report not found');
    }
    
    // Decode report data
    $reportData = json_decode($report['report_data'], true);
    
} catch (Exception $e) {
    $error = $e->getMessage();
}

// Add page-specific scripts
$page_scripts = [
    'assets/js/chart.min.js',
    'assets/js/report_view.js'
];

// Generate content
$content = <<<HTML
<div class="card">
    <div class="card-header d-flex justify-content-between align-items-center">
        <h5 class="mb-0">Report: {$report['report_type']}</h5>
        <div class="btn-group">
            <button type="button" class="btn btn-sm btn-outline-primary" onclick="window.print()">
                <i class="bi bi-printer"></i> Print
            </button>
            <a href="api/download_report.php?id={$reportId}&format=pdf" class="btn btn-sm btn-outline-secondary">
                <i class="bi bi-file-pdf"></i> PDF
            </a>
            <a href="api/download_report.php?id={$reportId}&format=excel" class="btn btn-sm btn-outline-success">
                <i class="bi bi-file-excel"></i> Excel
            </a>
        </div>
    </div>
    <div class="card-body">
        <!-- Report Header -->
        <div class="row mb-4">
            <div class="col-md-6">
                <h6 class="text-muted">Report Details</h6>
                <table class="table table-sm">
                    <tr>
                        <th>Type:</th>
                        <td>{$report['report_type']}</td>
                    </tr>
                    <tr>
                        <th>Period:</th>
                        <td>{$report['period']}</td>
                    </tr>
                    <tr>
                        <th>Date Range:</th>
                        <td>{$report['start_date']} to {$report['end_date']}</td>
                    </tr>
                    <tr>
                        <th>Class:</th>
                        <td>{$report['class_name']}</td>
                    </tr>
                    <tr>
                        <th>Student:</th>
                        <td>{$report['student_name'] ?? 'All Students'}</td>
                    </tr>
                    <tr>
                        <th>Generated By:</th>
                        <td>{$report['generated_by']}</td>
                    </tr>
                    <tr>
                        <th>Generated On:</th>
                        <td>{$report['generated_at']}</td>
                    </tr>
                </table>
            </div>
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h6 class="card-title">Summary</h6>
                        <div id="summaryChart" style="height: 200px;"></div>
                    </div>
                </div>
            </div>
        </div>
        
        <!-- Report Content -->
        <div class="report-content">
HTML;

// Add report-specific content based on type
switch ($report['report_type']) {
    case 'academic':
        $content .= generateAcademicReportContent($reportData);
        break;
    case 'attendance':
        $content .= generateAttendanceReportContent($reportData);
        break;
    case 'health':
        $content .= generateHealthReportContent($reportData);
        break;
    case 'discipline':
        $content .= generateDisciplineReportContent($reportData);
        break;
    case 'co_curricular':
        $content .= generateCoCurricularReportContent($reportData);
        break;
    case 'financial':
        $content .= generateFinancialReportContent($reportData);
        break;
    case 'passout':
        $content .= generatePassoutReportContent($reportData);
        break;
}

$content .= <<<HTML
        </div>
    </div>
</div>

<script>
// Initialize charts and visualizations
document.addEventListener('DOMContentLoaded', function() {
    initializeReportCharts('{$report['report_type']}', {$report['report_data']});
});
</script>
HTML;

// Helper functions for generating report-specific content
function generateAcademicReportContent($data) {
    $content = <<<HTML
    <div class="row mb-4">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Performance Overview</h6>
                    <div id="performanceChart" style="height: 300px;"></div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Subject Distribution</h6>
                    <div id="subjectChart" style="height: 300px;"></div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="card mb-4">
        <div class="card-body">
            <h6 class="card-title">Detailed Results</h6>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Subject</th>
                            <th>Score</th>
                            <th>Grade</th>
                            <th>Date</th>
                        </tr>
                    </thead>
                    <tbody>
HTML;
    
    foreach ($data as $record) {
        $content .= <<<HTML
        <tr>
            <td>{$record['subject_name']}</td>
            <td>{$record['score']}</td>
            <td>{$record['grade']}</td>
            <td>{$record['exam_date']}</td>
        </tr>
HTML;
    }
    
    $content .= <<<HTML
                    </tbody>
                </table>
            </div>
        </div>
    </div>
HTML;
    
    return $content;
}

function generateAttendanceReportContent($data) {
    $content = <<<HTML
    <div class="row mb-4">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Attendance Overview</h6>
                    <div id="attendanceChart" style="height: 300px;"></div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Attendance Trends</h6>
                    <div id="attendanceTrendChart" style="height: 300px;"></div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="card mb-4">
        <div class="card-body">
            <h6 class="card-title">Attendance Records</h6>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Status</th>
                            <th>Remarks</th>
                        </tr>
                    </thead>
                    <tbody>
HTML;
    
    foreach ($data as $record) {
        $content .= <<<HTML
        <tr>
            <td>{$record['date']}</td>
            <td><span class="badge bg-{$record['status'] === 'present' ? 'success' : 'danger'}">{$record['status']}</span></td>
            <td>{$record['remarks']}</td>
        </tr>
HTML;
    }
    
    $content .= <<<HTML
                    </tbody>
                </table>
            </div>
        </div>
    </div>
HTML;
    
    return $content;
}

function generateHealthReportContent($data) {
    $content = <<<HTML
    <div class="row mb-4">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Health Status Distribution</h6>
                    <div id="healthStatusChart" style="height: 300px;"></div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Health Incidents Timeline</h6>
                    <div id="healthTimelineChart" style="height: 300px;"></div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="card mb-4">
        <div class="card-body">
            <h6 class="card-title">Health Records</h6>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Status</th>
                            <th>Description</th>
                            <th>Action Taken</th>
                        </tr>
                    </thead>
                    <tbody>
HTML;
    
    foreach ($data as $record) {
        $content .= <<<HTML
        <tr>
            <td>{$record['record_date']}</td>
            <td><span class="badge bg-{$record['health_status'] === 'healthy' ? 'success' : 'warning'}">{$record['health_status']}</span></td>
            <td>{$record['description']}</td>
            <td>{$record['action_taken']}</td>
        </tr>
HTML;
    }
    
    $content .= <<<HTML
                    </tbody>
                </table>
            </div>
        </div>
    </div>
HTML;
    
    return $content;
}

// Add similar functions for other report types...
?> 